# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Falsification Pooler Experimentalist
repo_url: 'https://github.com/AutoResearch/autora-experimentalist-falsification'

nav:
- Pooler:
  - Home: 'index-pooler.md'
  - Quickstart: 'quickstart-pooler.md'
  - Examples:
    - Basic Usage: 'basic-usage-pooler.ipynb'
- Sampler:
  - Home: 'index-sampler.md'
  - Quickstart: 'quickstart-sampler.md'
  - Examples:
    - Basic Usage: 'basic-usage-sampler.ipynb'
