# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Falsification Pooler
repo_url: 'https://github.com/AutoResearch/autora-experimentalist-falsification-sampler'

nav:
- Home: 'index.md'
- Quickstart: 'quickstart.md'
- Examples:
  - Basic Usage: 'basic-usage.ipynb'
