# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Falsification Experimentalist
repo_url: 'https://github.com/AutoResearch/autora-experimentalist-falsification'

nav:
- Home: 'index.md'
- Quickstart: 'quickstart.md'
- Examples:
  - Basic Usage: 'Basic Usage.ipynb'
