# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Theorist Template
repo_url: 'https://github.com/autoresearch/autora-theorist-template'

nav:
- 'index.md'
- 'example.ipynb'
- Code Reference: reference/
